version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:mongodb
    networks:
      - mynetwork
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DBNAME: cms-naqib
    # ports:
    #   - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mynetwork

volumes:
  mongodb-data:

networks:
  mynetwork:
    external: true
