version: "2"
services:
  client:
    image: client_nextjs
    container_name: client_nextjs
    build: ./client_nextjs/
    # network_mode: bridge

    environment:
      - NODE_ENV=docker_production
    ports:
      - "8001:7001"
    depends_on:
      #   - mongo
      - cms
    # volumes:
      #- /data/naqib.info_static_content:/data/naqib.info_static_content:ro
      # - /data:/data

  cms:
    container_name: cms_keystone
    build: ./cms_keystone/
    # network_mode: bridge
    environment:
      - NODE_ENV=docker_production
    ports:
      - "8010:5000"
    volumes:
      - /data/naqib.info_static_content:/data/naqib.info_static_content:rw

# docker-compose up --build -d
