version: "3.8"

services:
  client:
    #    image: client_nextjs
    # image: naqibprio/naqibinfo:1.04
    container_name: client_nextjs
    build: ./client_nextjs/
    hostname: client
    networks:
      - naqibinfo-net
      # - host

    env_file:
      - ./config/.env
      # - ./config/.env.prod

    ports:
      - "8001:7001"
    depends_on:
      - cms
    restart: unless-stopped

  cms:
    # image: naqibprio/naqibinfo_cms:1.00
    build: ./cms_keystone/
    container_name: cms_keystone
    hostname: cms
    networks:
      - naqibinfo-net

    env_file:
      - ./config/.env
      # - ./config/.env.prod
    ports:
      - "8002:5000"
    depends_on:
      - mongodb
    restart: unless-stopped
  
  mongodb:
    image: mongo:latest
    hostname: mongodb
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_DBNAME: cms-naqib
    # ports:
    #   - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - naqibinfo-net
networks:
  naqibinfo-net:
    external: false # specifies that this network has been created outside of Compose
    driver: bridge
    name: naqibinfo-net
  # host: 
  #   external: false
  #   driver: host
  #   name: host
