version: "2"
services:
  client:
    image: client_nextjs
    container_name: client_nextjs
    build: ./client_nextjs/
    # network_mode: bridge

    environment:
      - NODE_ENV=docker_production

    ports:
      - "8001:7001"
    depends_on:
      #   - mongo
      - cms
    volumes:
      - /data/naqib.info_static_content:/data/naqib.info_static_content:ro

  cms:
    container_name: cms_keystone
    build: ./cms_keystone/
    # network_mode: bridge
    environment:
      - NODE_ENV=docker_production
      - cookieSecret=95a0c37c6a2942ca6a62fbd4fa45b7646aaf1c5a3f0efa64a526dace27700926
      - CLOUDINARY_CLOUD_NAME=ajmain
      - CLOUDINARY_KEY=665259314945228
      - CLOUDINARY_SECRET=zFIP4k-EufLITZBpj4KvqQLa22w
    ports:
      - "8010:5000"
    volumes:
      - /data/naqib.info_static_content:/data/naqib.info_static_content:rw
      - /etc/letsencrypt/live/naqib.info/:/cert:ro
# docker-compose up --build -d
